//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodHarbor.RecipeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recipe", Namespace="http://foodharbor.com/")]
    [System.SerializableAttribute()]
    public partial class Recipe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RecipeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IngredientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RecipeID {
            get {
                return this.RecipeIDField;
            }
            set {
                if ((this.RecipeIDField.Equals(value) != true)) {
                    this.RecipeIDField = value;
                    this.RaisePropertyChanged("RecipeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RecipeName {
            get {
                return this.RecipeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipeNameField, value) != true)) {
                    this.RecipeNameField = value;
                    this.RaisePropertyChanged("RecipeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Ingredients {
            get {
                return this.IngredientsField;
            }
            set {
                if ((object.ReferenceEquals(this.IngredientsField, value) != true)) {
                    this.IngredientsField = value;
                    this.RaisePropertyChanged("Ingredients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Method {
            get {
                return this.MethodField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodField, value) != true)) {
                    this.MethodField = value;
                    this.RaisePropertyChanged("Method");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://foodharbor.com/", ConfigurationName="RecipeService.RecipesServiceSoap")]
    public interface RecipesServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetRecipesResult from namespace http://foodharbor.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://foodharbor.com/GetRecipes", ReplyAction="*")]
        FoodHarbor.RecipeService.GetRecipesResponse GetRecipes(FoodHarbor.RecipeService.GetRecipesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://foodharbor.com/GetRecipes", ReplyAction="*")]
        System.Threading.Tasks.Task<FoodHarbor.RecipeService.GetRecipesResponse> GetRecipesAsync(FoodHarbor.RecipeService.GetRecipesRequest request);
        
        // CODEGEN: Generating message contract since element name recipeName from namespace http://foodharbor.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://foodharbor.com/AddRecipe", ReplyAction="*")]
        FoodHarbor.RecipeService.AddRecipeResponse AddRecipe(FoodHarbor.RecipeService.AddRecipeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://foodharbor.com/AddRecipe", ReplyAction="*")]
        System.Threading.Tasks.Task<FoodHarbor.RecipeService.AddRecipeResponse> AddRecipeAsync(FoodHarbor.RecipeService.AddRecipeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRecipesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecipes", Namespace="http://foodharbor.com/", Order=0)]
        public FoodHarbor.RecipeService.GetRecipesRequestBody Body;
        
        public GetRecipesRequest() {
        }
        
        public GetRecipesRequest(FoodHarbor.RecipeService.GetRecipesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRecipesRequestBody {
        
        public GetRecipesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRecipesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecipesResponse", Namespace="http://foodharbor.com/", Order=0)]
        public FoodHarbor.RecipeService.GetRecipesResponseBody Body;
        
        public GetRecipesResponse() {
        }
        
        public GetRecipesResponse(FoodHarbor.RecipeService.GetRecipesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://foodharbor.com/")]
    public partial class GetRecipesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FoodHarbor.RecipeService.Recipe[] GetRecipesResult;
        
        public GetRecipesResponseBody() {
        }
        
        public GetRecipesResponseBody(FoodHarbor.RecipeService.Recipe[] GetRecipesResult) {
            this.GetRecipesResult = GetRecipesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRecipeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRecipe", Namespace="http://foodharbor.com/", Order=0)]
        public FoodHarbor.RecipeService.AddRecipeRequestBody Body;
        
        public AddRecipeRequest() {
        }
        
        public AddRecipeRequest(FoodHarbor.RecipeService.AddRecipeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://foodharbor.com/")]
    public partial class AddRecipeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string recipeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ingredients;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string method;
        
        public AddRecipeRequestBody() {
        }
        
        public AddRecipeRequestBody(string recipeName, string ingredients, string method) {
            this.recipeName = recipeName;
            this.ingredients = ingredients;
            this.method = method;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRecipeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRecipeResponse", Namespace="http://foodharbor.com/", Order=0)]
        public FoodHarbor.RecipeService.AddRecipeResponseBody Body;
        
        public AddRecipeResponse() {
        }
        
        public AddRecipeResponse(FoodHarbor.RecipeService.AddRecipeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddRecipeResponseBody {
        
        public AddRecipeResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RecipesServiceSoapChannel : FoodHarbor.RecipeService.RecipesServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecipesServiceSoapClient : System.ServiceModel.ClientBase<FoodHarbor.RecipeService.RecipesServiceSoap>, FoodHarbor.RecipeService.RecipesServiceSoap {
        
        public RecipesServiceSoapClient() {
        }
        
        public RecipesServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecipesServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecipesServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecipesServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FoodHarbor.RecipeService.GetRecipesResponse FoodHarbor.RecipeService.RecipesServiceSoap.GetRecipes(FoodHarbor.RecipeService.GetRecipesRequest request) {
            return base.Channel.GetRecipes(request);
        }
        
        public FoodHarbor.RecipeService.Recipe[] GetRecipes() {
            FoodHarbor.RecipeService.GetRecipesRequest inValue = new FoodHarbor.RecipeService.GetRecipesRequest();
            inValue.Body = new FoodHarbor.RecipeService.GetRecipesRequestBody();
            FoodHarbor.RecipeService.GetRecipesResponse retVal = ((FoodHarbor.RecipeService.RecipesServiceSoap)(this)).GetRecipes(inValue);
            return retVal.Body.GetRecipesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FoodHarbor.RecipeService.GetRecipesResponse> FoodHarbor.RecipeService.RecipesServiceSoap.GetRecipesAsync(FoodHarbor.RecipeService.GetRecipesRequest request) {
            return base.Channel.GetRecipesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FoodHarbor.RecipeService.GetRecipesResponse> GetRecipesAsync() {
            FoodHarbor.RecipeService.GetRecipesRequest inValue = new FoodHarbor.RecipeService.GetRecipesRequest();
            inValue.Body = new FoodHarbor.RecipeService.GetRecipesRequestBody();
            return ((FoodHarbor.RecipeService.RecipesServiceSoap)(this)).GetRecipesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FoodHarbor.RecipeService.AddRecipeResponse FoodHarbor.RecipeService.RecipesServiceSoap.AddRecipe(FoodHarbor.RecipeService.AddRecipeRequest request) {
            return base.Channel.AddRecipe(request);
        }
        
        public void AddRecipe(string recipeName, string ingredients, string method) {
            FoodHarbor.RecipeService.AddRecipeRequest inValue = new FoodHarbor.RecipeService.AddRecipeRequest();
            inValue.Body = new FoodHarbor.RecipeService.AddRecipeRequestBody();
            inValue.Body.recipeName = recipeName;
            inValue.Body.ingredients = ingredients;
            inValue.Body.method = method;
            FoodHarbor.RecipeService.AddRecipeResponse retVal = ((FoodHarbor.RecipeService.RecipesServiceSoap)(this)).AddRecipe(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FoodHarbor.RecipeService.AddRecipeResponse> FoodHarbor.RecipeService.RecipesServiceSoap.AddRecipeAsync(FoodHarbor.RecipeService.AddRecipeRequest request) {
            return base.Channel.AddRecipeAsync(request);
        }
        
        public System.Threading.Tasks.Task<FoodHarbor.RecipeService.AddRecipeResponse> AddRecipeAsync(string recipeName, string ingredients, string method) {
            FoodHarbor.RecipeService.AddRecipeRequest inValue = new FoodHarbor.RecipeService.AddRecipeRequest();
            inValue.Body = new FoodHarbor.RecipeService.AddRecipeRequestBody();
            inValue.Body.recipeName = recipeName;
            inValue.Body.ingredients = ingredients;
            inValue.Body.method = method;
            return ((FoodHarbor.RecipeService.RecipesServiceSoap)(this)).AddRecipeAsync(inValue);
        }
    }
}
